### PR TITLE
check out the modified readme

### PR DESCRIPTION
**Pull request by Zainab-ik**
Thanks for reading my pull requests

### CODE REVIEW

**Comment by MasterIfeanyi** [comment]
Great work @Zainab-ik

**Comment by Zainab-ik** [comment]
Thank you, is there anything else you'd like me to add

**Comment by Zainab-ik** [comment]
And the assignation

**Comment by Zainab-ik** [comment]
Apologies, kindly re-assign. That was an error from my end. thank you

**Comment by Zainab-ik** [comment]
thank you

**Pull request merged**
